# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

load(
    "//common:common.bzl",
    "execute",
    "get_host_environ",
)
load(
    "//gpu:compiler_common_tools.bzl",
    "get_cxx_inc_directories",
)

_LLVM_VERSION = "LLVM_VERSION"

def _get_platform_arch(ctx):
    """Gets current platform architecture"""
    if ctx.os.arch == "amd64":
        return "x86_64"
    else:
        return ctx.os.arch

def _is_compatible_arch(ctx):
    """Checks if LLVM compatible with current platform"""
    return ctx.attr.name.endswith(_get_platform_arch(ctx))

def _get_llvm_version_flag(ctx):
    """Returns LLVM version put as environment variable"""
    return get_host_environ(ctx, _LLVM_VERSION)

def _get_llvm_version(ctx):
    """Returns the LLVM version from the LLVM_VERSION repository environment variable, defaulting otherwise"""
    ver = _get_llvm_version_flag(ctx) or ctx.attr.default_version

    if not ver:
        fail("Specify LLVM version in .bazelrc file. Example: --repo_env=LLVM_VERSION=21")

    return ver

def _get_llvm_label(ctx, ver):
    """Returns the LLVM label for the specified version"""
    llvm_dict = ctx.attr.versions
    for llvm_label in llvm_dict.keys():
        if llvm_dict[llvm_label] == ver:
            return llvm_label

    return None

def _create_version_file(ctx, major_version):
    """Writes the LLVM version to the version.bzl file"""
    ctx.file(
        "version.bzl",
        "VERSION = \"{}\"".format(major_version),
    )

def _get_clang_resource_dir(ctx, clang_path):
    """Get clang resource directory using -print-resource-dir."""
    result = execute(ctx, [clang_path, "-print-resource-dir"])
    if result.return_code == 0:
        return result.stdout.strip()
    return ""

def _get_clang_version(ctx, clang_path):
    """Get clang version."""
    result = execute(ctx, [clang_path, "--version"])
    if result.return_code == 0:
        # Parse "clang version X.Y.Z" or "Ubuntu clang version X.Y.Z"
        for line in result.stdout.split("\n"):
            if "clang version" in line.lower():
                parts = line.split(" ")
                for i, part in enumerate(parts):
                    if part == "version" and i + 1 < len(parts):
                        return parts[i + 1]
    return ""

def _create_clang_bzl(ctx, llvm_repo_name, llvm_label):
    """Creates clang.bzl file with hermetic clang configuration by detecting from clang."""
    # Get the path to clang binary in the underlying LLVM repo
    clang_path = ctx.path(Label("@@{}//:bin/clang".format(llvm_repo_name)))

    if not clang_path.exists:
        fail("Clang binary not found at {}".format(clang_path))

    # Detect configuration by calling clang
    resource_dir = _get_clang_resource_dir(ctx, str(clang_path))
    version = _get_clang_version(ctx, str(clang_path))
    include_dir = resource_dir + "/include" if resource_dir else ""

    # Get all include directories using the same method as local_clang_configure
    tf_sysroot = get_host_environ(ctx, "TF_SYSROOT", "")
    include_directories = get_cxx_inc_directories(
        ctx,
        str(clang_path),
        tf_sysroot,
    )

    # Ensure clang resource include directory is present and first
    if include_dir:
        include_directories = [d for d in include_directories if d != include_dir]
        include_directories = [include_dir] + include_directories

    # Get the external repo path prefix for the underlying LLVM repo
    # This is the path that will work in toolchain configuration
    external_prefix = "external/{}".format(llvm_repo_name)

    ctx.file("clang.bzl", """
# Auto-generated by llvm repository rule
# LLVM repo: {llvm_repo_name}
# Version: {version}
# Detected by calling: {clang_path}

def hermetic_clang():
    \"\"\"Returns the hermetic clang compiler configuration.

    Returns a struct with:
    - Labels: Use these in Bazel rules (e.g., srcs, data)
    - Paths: Absolute paths detected from the clang binary
    \"\"\"
    return struct(
        found = True,
        version = "{version}",
        llvm_repo = "{llvm_repo_name}",
        # Labels for use in Bazel rules
        compiler_label = "@@{llvm_repo_name}//:bin/clang",
        includes_label = "@@{llvm_repo_name}//:includes",
        # Paths with external/ prefix for toolchain configuration
        compiler_path = "{external_prefix}/bin/clang",
        resource_dir = "{resource_dir}",
        include_dir = "{include_dir}",
        # Detected include directories (absolute paths)
        include_directories = {include_directories},
    )
""".format(
        llvm_repo_name = llvm_repo_name,
        version = version,
        clang_path = clang_path,
        external_prefix = external_prefix,
        resource_dir = resource_dir,
        include_dir = include_dir,
        include_directories = include_directories,
    ))

def _create_empty_clang_bzl(ctx):
    """Creates a dummy clang.bzl file when LLVM is not available."""
    ctx.file("clang.bzl", """
# LLVM not available for this platform
def hermetic_clang():
    return struct(
        found = False,
        version = "",
        llvm_repo = "",
        compiler_label = "",
        includes_label = "",
        compiler_path = "",
        resource_dir = "",
        include_dir = "",
        include_directories = [],
    )
""")

def _llvm_impl(ctx):
    if not _is_compatible_arch(ctx):
        _create_version_file(ctx, "")
        _create_empty_clang_bzl(ctx)
        ctx.file("BUILD", "")
        return

    ver = _get_llvm_version(ctx)
    llvm_label = _get_llvm_label(ctx, ver)
    if not llvm_label:
        fail("Ensure LLVM {} support is added prior to use. Supported versions: {}"
            .format(ver, ", ".join(ctx.attr.versions.values())))

    _create_version_file(ctx, ver)
    _create_clang_bzl(ctx, llvm_label.repo_name, llvm_label)

    ctx.template(
        "BUILD",
        ctx.attr.build_file_tpl,
        {
            "%{llvm_repo_name}": llvm_label.repo_name,
        },
    )

llvm = repository_rule(
    implementation = _llvm_impl,
    attrs = {
        "default_version": attr.string(),
        "versions": attr.label_keyed_string_dict(
            allow_files = True,
            mandatory = True,
        ),
        "build_file_tpl": attr.label(mandatory = True),
    },
)
