#=====================================================================
# Not ManyLinux tag compliant libraries for usage in deps attribute
#=====================================================================

# Alias for cc_import
alias(
    name = "linux_x86_64_openmp",
    actual = "@sysroot_linux_x86_64//:openmp_import",
    visibility = ["//visibility:public"],
)

# Alias for cc_import
alias(
    name = "linux_aarch64_openmp",
    actual = "@sysroot_linux_aarch64//:openmp_import",
    visibility = ["//visibility:public"],
)
