# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""ROCm/HIPcc configuration information.

This file is auto-generated by hipcc_configure.bzl and provides information
about the configured ROCm/HIPcc installation.
"""

def hipcc_config():
    """Returns the ROCm/HIPcc configuration information.

    Returns:
        A struct with the following fields:
            - gpu_architectures: List of AMDGPU target architectures (e.g., ["gfx906", "gfx908"])
            - hipcc_path: Path to the hipcc compiler binary
            - rocm_root: Path to the ROCm root within the distribution (for file labels)
            - lib_paths: List of library paths (for multiple ROCm paths setup)
            - version_number: ROCm version number
            - clang_version: Clang version string
            - include_paths: System include paths (computed from rocm_root and clang_version)
    """
    rocm_root = "%{rocm_root}"
    clang_version = "%{clang_version}"

    # System include paths - these depend on ROCm installation location
    include_paths = [
        rocm_root + "/llvm/lib/clang/" + clang_version + "/include",
        rocm_root + "/include",
    ]

    return struct(
        gpu_architectures = %{rocm_gpu_architectures},
        hipcc_path = "%{hipcc_path}",
        rocm_root = rocm_root,
        clang_version = clang_version,
        lib_paths = %{rocm_lib_paths},
        version_number = %{rocm_version_number},
        include_paths = include_paths,
    )
